### ISSUE TITLE
aim assist dont work fr

### ISSUE THREAD

**Issue by AstroOnYT** [pesshown/Cheatbreaker-Ghost-Client-Mod-1.8.9#1]

**Comment by pesshown** [comment]
AimAssist work only if you are sprinting and on ground.

**Comment by pesshown** [comment]
**You can decompile source and remove it.**

![sss](https://user-images.githubusercontent.com/28790589/188315038-63f0d23e-77db-407a-a566-0a2f38d32d52.png)
